server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: fei-audit-log

c2s:
  fhir:
    publish:
      serverUrl:
        resource: http://ocp.consent2share.org/fhir/baseDstu3
        # Set 'patient' URL if the patient resource is available in another server different from the 'resource' server
        # patient: http://localhost:8470
      clientSocketTimeoutInMs: 768000
      use-create-for-update: false
      encoding: json
    consent:
      codeSystem: https://bhits.github.io/consent2share
      # If 'patientReference' is true, then patient in a FHIR consent refers to a FHIR Patient Resource
      patientReference: false
    audit:
      enable: true


